[env:m5stack-stickcplus]
extends = esp32_base
board = m5stick-c
monitor_filters = esp32_exception_decoder
build_src_filter = 
  ${esp32_base.build_src_filter}
build_flags = 
  ${esp32_base.build_flags} -I variants/m5stack_stickcplus

# Driver IC:ST7789v2
# Resolution:135 * 240
# ESP32	GPIO15	GPIO13	GPIO23	GPIO18	GPIO5
#     TFT_MOSI	TFT_CLK	TFT_DC	TFT_RST	TFT_CS
  -DST7789_DRIVER
  -DM5STACK
  -DUSER_SETUP_LOADED
  -DTFT_SDA_READ
  -DTFT_DRIVER=0x9341
  -DTFT_MISO=19
  -DTFT_MOSI=15
  -DTFT_SCLK=13
  -DTFT_CS=5
  -DTFT_DC=23
  -DTFT_RST=18
  #-DTFT_BL=32
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=16000000
  -DDISABLE_ALL_LIBRARY_WARNINGS
lib_ignore =
  m5stack-core
lib_deps = 
  ${esp32_base.lib_deps}
  lovyan03/LovyanGFX@^1.1.8
